
name: linux Build

on:
    workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest 

    env:
      Solution_Name: CRBDL.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Project_Directory: dbfal
      
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Build dotnet
      run: |
          ./dbfal/Setup-AppDir.sh
          cd ./dbfal/bin
          wget https://github.com/AppImage/appimagetool/releases/download/1.9.1/appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage ./AppDir/ ./DBFAL-x86_64.AppImage

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: DBFAL-linux-x64
        path: |
          ${{ env.Project_Directory }}/bin/DBFAL-x86_64.AppImage
